// Every table in the schema, for full-database disaster-recovery
// snapshots (lib/backup/snapshot.ts) -- deliberately broader than the
// curated, business-facing list in app/(portal)/settings/data-export,
// which only covers what a Director would want as a working CSV export.
export const ALL_TABLES = [
  "acting_ceo_periods",
  "announcements",
  "approval_policies",
  "approval_requests",
  "audit_log",
  "chat_channel_members",
  "chat_channels",
  "chat_messages",
  "conflict_register",
  "contacts",
  "contracts",
  "decision_escalation_guide",
  "decisions",
  "documents",
  "email_portfolio_links",
  "engagement_checklist_items",
  "engagement_checklist_templates",
  "engagement_notes",
  "engagement_signoffs",
  "engagements",
  "expenses",
  "finance_budgets",
  "form_assignments",
  "form_submissions",
  "forms",
  "integration_settings",
  "internal_projects",
  "kb_articles",
  "leave_requests",
  "mailbox_connections",
  "meetings",
  "notification_preferences",
  "notifications",
  "onboarding_tasks",
  "partner_actions",
  "partner_contacts",
  "partner_documents",
  "partner_messages",
  "partner_report_schedule",
  "portfolio_actions",
  "portfolio_companies",
  "portfolio_kpis",
  "project_budget_items",
  "project_milestones",
  "project_risks",
  "project_tasks",
  "shared_mailbox_access",
  "signature_requests",
  "signature_signers",
  "staff_profiles",
  "users",
] as const;
